server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  application:
    name: Ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/Ecommerce
    username: postgres
    password: vikash

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format-sql: true


  security:
    user:
      name: admin
      password: admin